name: Example of context variables
on: push
jobs:
  context_env:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
          echo "This workflow is triggered by ${{ github.actor }}"
          echo "The repository name is ${{ github.repository }}"
      - name: Print github environment variable
        run: echo "This is the runner $RUNNER_ENVIRONMENT"
      - name: Print environment variables
        run: printenv
