name: Demo Build and Deploy
on: 
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - synchronize
jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Build on pull request
        run: echo "Building the application."
  Deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Deploy the application
        run: echo "deploying the application"
        
