# This is a basic workflow to help you get started with Actions
name: Multi line cmd
on: workflow_call
jobs:
  Multi-line:
    runs-on: ubuntu-latest
    steps:
      - name: multi echo
        run: |
          echo "this is line one"
          echo "This is line 2"
         
