name: If condition example
on: 
  push:
    branches:
      - main
      - develop
jobs:
  if-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref == 'refs/heads/main'
        run: echo "Running this step on main branch"
      - name: Run in another branch
        run: echo "Running this branch"
