name: Example of output variables
on: workflow_dispatch
jobs:
  Build:
    outputs:
      version: ${{ steps.step1.outputs.version}}
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "We are deploying the app with version ${{needs.Build.outputs.version}}"
  
